name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy on VPS
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: root
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF 2>&1 | tee ssh-deploy.log
            set -eux
            cd /var/www/truyen-tranh
            git pull origin main

            docker compose up -d --build
            if [ $? -eq 0 ]; then
              echo "Docker-compose build and up SUCCESS"
            else
              echo "Docker-compose build and up FAILED"
              exit 1
            fi

            docker ps
            docker-compose logs --tail=20

            # Optional: kiểm tra app chạy bằng curl (cập nhật port phù hợp)
            # curl -I http://localhost:8000
          EOF
